import Head from 'next/head'
import Main from "../components/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ANARDONI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Main/>
    </div>
  )
}
