import Head from 'next/head'
import Main from "../components/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DIGIKALA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.digikala.com/favicon-16x16.png" />
      </Head>
        <Main/>
    </div>
  )
}
